device.profile.priority.rules = [
  {
    matches = [
      {
        device.name = "~alsa_card.*"
      }
    ]
    actions = {
      update-props = {
        priorities = [
          "HiFi (HDMI1, HDMI2, HDMI3, Mic1, Mic2, Speaker)"
        ]
      }
    }
  }
]
