# =============================================================================
# Kitty Theme Colors - Everforest Light
# =============================================================================

# Window borders
active_border_color #8da101
inactive_border_color #e5dfc5
bell_border_color #f85552

# Cursor
cursor #5c6a72
cursor_text_color #e0dcc7

# URL
url_color #3a94c5

# Tabs
active_tab_foreground   #e0dcc7
active_tab_background   #8da101
inactive_tab_foreground #5c6a72
inactive_tab_background #f4ede8
tab_bar_background      #e0dcc7

# Color Scheme
background #fdf6e3
foreground #5c6a72
selection_background #bdbaa3
selection_foreground #5c6a72

# Black
color0 #f4ede8
color8 #bdbaa3

# Red
color1 #f85552
color9 #f85552

# Green
color2  #8da101
color10 #8da101

# Yellow
color3  #dfa000
color11 #dfa000

# Blue
color4  #3a94c5
color12 #3a94c5

# Magenta / Mauve
color5  #df69ba
color13 #df69ba

# Cyan / Teal
color6  #35a77c
color14 #35a77c

# White
color7  #5c6a72
color15 #2d353b
