# =============================================================================
# Kitty Theme Colors - Catppuccin Frappé
# =============================================================================

# Window borders
active_border_color #ca9ee6
inactive_border_color #414559
bell_border_color #e78284

# Cursor
cursor #f2d5cf
cursor_text_color #232634

# URL
url_color #8caaee

# Tabs
active_tab_foreground   #232634
active_tab_background   #ca9ee6
inactive_tab_foreground #c6d0f5
inactive_tab_background #292c3c
tab_bar_background      #232634

# Color Scheme
background #303446
foreground #c6d0f5
selection_background #626880
selection_foreground #c6d0f5

# Black
color0 #51576d
color8 #626880

# Red
color1 #e78284
color9 #e78284

# Green
color2  #a6d189
color10 #a6d189

# Yellow
color3  #e5c890
color11 #e5c890

# Blue
color4  #8caaee
color12 #8caaee

# Magenta / Mauve
color5  #ca9ee6
color13 #ca9ee6

# Cyan / Teal
color6  #81c8be
color14 #81c8be

# White
color7  #b5bfe2
color15 #a5b0d6
