# =============================================================================
# Kitty Theme Colors - One Light Pro
# =============================================================================

# Window borders
active_border_color #4078f2
inactive_border_color #e0e0e0
bell_border_color #e45649

# Cursor
cursor #383a42
cursor_text_color #e5e5e6

# URL
url_color #4078f2

# Tabs
active_tab_foreground   #e5e5e6
active_tab_background   #4078f2
inactive_tab_foreground #383a42
inactive_tab_background #f0f0f0
tab_bar_background      #e5e5e6

# Color Scheme
background #fafafa
foreground #383a42
selection_background #a0a1a7
selection_foreground #383a42

# Black
color0 #e5e5e6
color8 #a0a1a7

# Red
color1 #e45649
color9 #e45649

# Green
color2  #50a14f
color10 #50a14f

# Yellow
color3  #c18401
color11 #c18401

# Blue
color4  #4078f2
color12 #4078f2

# Magenta / Mauve
color5  #a626a4
color13 #a626a4

# Cyan / Teal
color6  #0184bc
color14 #0184bc

# White
color7  #4f525d
color15 #383a42
