# =============================================================================
# Fuzzel Configuration
# Modern, lightweight Wayland application launcher & dmenu
# Catppuccin Mocha Theme
# =============================================================================

[main]
font=JetBrainsMono Nerd Font:weight=bold:size=12
prompt="   Search: "
icon-theme=Papirus-Dark
icons-enabled=yes
show-actions=no
terminal=kitty
lines=8
width=36
tabs=4
horizontal-pad=22
vertical-pad=16
inner-pad=10
image-size-ratio=0.5
line-height=26
letter-spacing=0
layer=overlay
exit-on-keyboard-focus-loss=yes

[colors]
# Dracula RGBA
background=21222cf0
text=f8f8f2ff
prompt=bd93f9ff
placeholder=6272a4ff
input=f8f8f2ff
match=bd93f9ff
selection=343746ff
selection-text=ffffffef
selection-match=bd93f9ff
border=bd93f9aa

[border]
width=2
radius=16

[dmenu]
mode=text
exit-immediately-if-empty=no
