# -*- conf -*-
# =============================================================================
# Foot Theme Colors - Gruvbox Light
# =============================================================================

[colors-dark]
alpha=0.92
foreground=3c3836
background=fbf1c7

regular0=ebdbb2
regular1=9d0006
regular2=79740e
regular3=b57614
regular4=076678
regular5=8f3f71
regular6=427b58
regular7=3c3836

bright0=928374
bright1=cc241d
bright2=98971a
bright3=d79921
bright4=458588
bright5=b16286
bright6=689d6a
bright7=282828

cursor=ebdbb2 ebdbb2
selection-foreground=3c3836
selection-background=a89984
urls=076678
