#!/usr/bin/env python3
"""
Hyprland Screen Resolution & Display Scaling Manager
Provides an interactive Wofi menu and keyboard shortcuts to switch screen resolution and display scaling.
"""

import sys
import json
import subprocess
import os
import re

CONFIG_MONITORS_FILE = os.path.expanduser("~/.config/hypr/modules/monitors.lua")

def run_cmd(cmd):
    try:
        res = subprocess.run(cmd, capture_output=True, text=True, check=True)
        return res.stdout.strip()
    except Exception:
        return None

def get_monitors():
    raw = run_cmd(["hyprctl", "monitors", "-j"])
    if not raw:
        return []
    try:
        return json.loads(raw)
    except Exception:
        return []

def get_focused_monitor():
    monitors = get_monitors()
    for m in monitors:
        if m.get("focused"):
            return m
    if monitors:
        return monitors[0]
    return None

def show_notification(title, body, icon="video-display"):
    run_cmd([
        "notify-send",
        "-r", "9120",
        "-t", "2000",
        "-u", "low",
        "-a", "Hyprland Display",
        "-i", icon,
        "-h", "string:x-canonical-private-synchronous:screen_resolution",
        title,
        body
    ])

def apply_resolution(monitor_name, mode, scale, save_config=False):
    lua_code = f'hl.monitor({{ output = "{monitor_name}", mode = "{mode}", position = "auto", scale = {scale} }})'
    res = run_cmd(["hyprctl", "eval", lua_code])

    show_notification(
        f"🖥️ Display Configured: {monitor_name}",
        f"Resolution: <b>{mode}</b>\nScaling: <b>{scale}x ({int(float(scale)*100)}%)</b>"
    )

    if save_config:
        save_to_monitors_lua(monitor_name, mode, scale)

def save_to_monitors_lua(monitor_name, mode, scale):
    content = f"""------------------
---- MONITORS ----
------------------

-- Auto-generated by resolution manager
hl.monitor({{
    output   = "{monitor_name}",
    mode     = "{mode}",
    position = "auto",
    scale    = {scale},
}})
"""
    try:
        with open(CONFIG_MONITORS_FILE, "w") as f:
            f.write(content)
    except Exception as e:
        print(f"Failed to save monitors.lua: {e}", file=sys.stderr)

def open_wofi_menu(prompt, options):
    input_str = "\n".join(options)
    import shutil
    if shutil.which("fuzzel"):
        cmd = ["fuzzel", "--dmenu", "--prompt", f"{prompt}: ", "--width", "38", "--lines", "10"]
    else:
        cmd = [
            "wofi",
            "--dmenu",
            "--prompt", prompt,
            "--width", "420",
            "--height", "380",
            "--cache-file", "/dev/null",
            "--hide-scroll",
            "--allow-markup",
            "--insensitive"
        ]
    try:
        proc = subprocess.Popen(
            cmd,
            stdin=subprocess.PIPE,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True
        )
        stdout, _ = proc.communicate(input=input_str)
        return stdout.strip()
    except Exception:
        return ""

def set_exact_scale(target_scale):
    mon = get_focused_monitor()
    if not mon:
        return
    name = mon.get("name", "eDP-1")
    current_w = mon.get("width", 1920)
    current_h = mon.get("height", 1080)
    current_rr = mon.get("refreshRate", 60.0)
    mode = f"{current_w}x{current_h}@{current_rr:.2f}"
    apply_resolution(name, mode, target_scale, save_config=False)

def scale_step(delta):
    mon = get_focused_monitor()
    if not mon:
        return
    name = mon.get("name", "eDP-1")
    current_scale = float(mon.get("scale", 1.0))
    current_w = mon.get("width", 1920)
    current_h = mon.get("height", 1080)
    current_rr = mon.get("refreshRate", 60.0)

    new_scale = round(current_scale + delta, 2)
    if new_scale < 0.5:
        new_scale = 0.5
    elif new_scale > 3.0:
        new_scale = 3.0

    mode = f"{current_w}x{current_h}@{current_rr:.2f}"
    apply_resolution(name, mode, new_scale, save_config=False)

def interactive_menu():
    mon = get_focused_monitor()
    if not mon:
        show_notification("Display Error", "No active monitor found")
        return

    name = mon.get("name", "eDP-1")
    current_w = mon.get("width", 1920)
    current_h = mon.get("height", 1080)
    current_rr = mon.get("refreshRate", 60.0)
    current_scale = mon.get("scale", 1.0)

    menu_options = [
        f"<b>★ Current:</b> {current_w}x{current_h} @ {current_scale}x scale",
        "─── DISPLAY SCALING ───",
        "🔍 Scale: 1.00x (100% - Native / Sharp)",
        "🔍 Scale: 1.25x (125% - Compact HiDPI)",
        "🔍 Scale: 1.50x (150% - Standard Recommended)",
        "🔍 Scale: 1.75x (175% - Comfortable)",
        "🔍 Scale: 2.00x (200% - Large UI / 2x)",
        "─── RESOLUTIONS ───",
        "🖥️ 1920x1080 @ 60Hz (Full HD)",
        "🖥️ 1600x900 @ 60Hz (HD+)",
        "🖥️ 1366x768 @ 60Hz (WXGA)",
        "🖥️ 1280x720 @ 60Hz (720p HD)",
        "🖥️ preferred (Hyprland Auto-detect)",
        "🖥️ highres (Highest available resolution)",
        "🖥️ highrr (Highest available refresh rate)",
        "─── ACTIONS ───",
        "💾 Save current settings as default",
    ]

    selected = open_wofi_menu(f"Resolution ({name})", menu_options)
    if not selected:
        return

    curr_mode = f"{current_w}x{current_h}@{current_rr:.2f}"

    if "Scale: 1.00x" in selected:
        apply_resolution(name, curr_mode, 1.0)
    elif "Scale: 1.25x" in selected:
        apply_resolution(name, curr_mode, 1.25)
    elif "Scale: 1.50x" in selected:
        apply_resolution(name, curr_mode, 1.5)
    elif "Scale: 1.75x" in selected:
        apply_resolution(name, curr_mode, 1.75)
    elif "Scale: 2.00x" in selected:
        apply_resolution(name, curr_mode, 2.0)
    elif "1920x1080" in selected:
        apply_resolution(name, "1920x1080@60", current_scale)
    elif "1600x900" in selected:
        apply_resolution(name, "1600x900@60", 1.0)
    elif "1366x768" in selected:
        apply_resolution(name, "1366x768@60", 1.0)
    elif "1280x720" in selected:
        apply_resolution(name, "1280x720@60", 1.0)
    elif "preferred" in selected:
        apply_resolution(name, "preferred", "auto")
    elif "highres" in selected:
        apply_resolution(name, "highres", "auto")
    elif "highrr" in selected:
        apply_resolution(name, "highrr", "auto")
    elif "Save current settings" in selected:
        save_to_monitors_lua(name, curr_mode, current_scale)
        show_notification("Display Settings Saved", f"Saved {name} ({curr_mode}, {current_scale}x) to monitors.lua")

def main():
    if len(sys.argv) > 1:
        arg = sys.argv[1].lower()
        if arg in ["scale_up", "scale+", "zoom_in"]:
            scale_step(0.1)
            return
        elif arg in ["scale_down", "scale-", "zoom_out"]:
            scale_step(-0.1)
            return
        elif arg.startswith("scale:") or arg.startswith("scale="):
            try:
                val = float(arg.split(":", 1)[-1].split("=", 1)[-1])
                set_exact_scale(val)
                return
            except ValueError:
                pass
        elif arg in ["1", "1.0", "1.00", "1x", "100%", "100"]:
            set_exact_scale(1.0)
            return
        elif arg in ["1.25", "1.25x", "125%", "125"]:
            set_exact_scale(1.25)
            return
        elif arg in ["1.5", "1.50", "1.5x", "150%", "150"]:
            set_exact_scale(1.5)
            return
        elif arg in ["1.75", "1.75x", "175%", "175"]:
            set_exact_scale(1.75)
            return
        elif arg in ["2", "2.0", "2.00", "2x", "200%", "200"]:
            set_exact_scale(2.0)
            return
        elif arg == "show":
            mon = get_focused_monitor()
            if mon:
                w, h = mon.get("width", 0), mon.get("height", 0)
                scale = mon.get("scale", 1.0)
                rr = mon.get("refreshRate", 60.0)
                name = mon.get("name", "Screen")
                show_notification(f"🖥️ {name} Resolution", f"<b>{w} × {h}</b> @ {rr:.2f}Hz\nScale: <b>{scale}x ({int(float(scale)*100)}%)</b>")
            return
        elif arg == "set" and len(sys.argv) >= 4:
            mon_name = sys.argv[2]
            mode = sys.argv[3]
            scale = sys.argv[4] if len(sys.argv) > 4 else "1.0"
            apply_resolution(mon_name, mode, scale, save_config=True)
            return

    interactive_menu()

if __name__ == "__main__":
    main()
