# =============================================================================
# Lazygit Configuration - Gruvbox Dark
# =============================================================================

gui:
  theme:
    activeBorderColor:
      - '#fabd2f'
      - bold
    inactiveBorderColor:
      - '#665c54'
    optionsTextColor:
      - '#458588'
    selectedLineBgColor:
      - '#3c3836'
    cherryPickedCommitBgColor:
      - '#504945'
    cherryPickedCommitFgColor:
      - '#fabd2f'
    unstagedChangesColor:
      - '#fb4934'
    defaultFgColor:
      - '#ebdbb2'
    searchingActiveBorderColor:
      - '#fabd2f'

git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never --line-numbers --hyperlinks --side-by-side
