# =============================================================================
# Lazygit Configuration - Everforest Dark
# =============================================================================

gui:
  theme:
    activeBorderColor:
      - '#a7c080'
      - bold
    inactiveBorderColor:
      - '#475258'
    optionsTextColor:
      - '#7fbbb3'
    selectedLineBgColor:
      - '#343f44'
    cherryPickedCommitBgColor:
      - '#3d484d'
    cherryPickedCommitFgColor:
      - '#a7c080'
    unstagedChangesColor:
      - '#e67e80'
    defaultFgColor:
      - '#d3c6aa'
    searchingActiveBorderColor:
      - '#dbbc7f'

git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never --line-numbers --hyperlinks --side-by-side
