# =============================================================================
# Lazygit Configuration - Dracula
# =============================================================================

gui:
  theme:
    activeBorderColor:
      - '#bd93f9'
      - bold
    inactiveBorderColor:
      - '#6272a4'
    optionsTextColor:
      - '#6272a4'
    selectedLineBgColor:
      - '#343746'
    cherryPickedCommitBgColor:
      - '#44475a'
    cherryPickedCommitFgColor:
      - '#bd93f9'
    unstagedChangesColor:
      - '#ff5555'
    defaultFgColor:
      - '#f8f8f2'
    searchingActiveBorderColor:
      - '#f1fa8c'

git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never --line-numbers --hyperlinks --side-by-side
