wallpaper = eDP-1,/home/kunal/Wallpaper/jms-kFHz9Xh3PPU-unsplash.jpg
wallpaper = HDMI-A-1,/home/kunal/Wallpaper/jms-kFHz9Xh3PPU-unsplash.jpg
wallpaper = ,/home/kunal/Wallpaper/jms-kFHz9Xh3PPU-unsplash.jpg
splash = false
