-- Auto-generated by theme_switcher.py for Hyprland
return {
    name            = "Everforest Dark",
    id              = "everforest",
    base            = "rgba(2d353bff)",
    mantle          = "rgba(232a2eff)",
    crust           = "rgba(1e2326ff)",
    surface0        = "rgba(343f44ff)",
    surface1        = "rgba(3d484dff)",
    surface2        = "rgba(475258ff)",
    text            = "rgba(d3c6aaff)",
    subtext0        = "rgba(9da9a0ff)",
    subtext1        = "rgba(bdc3afff)",
    active_border_1 = "rgba(a7c080ee)",
    active_border_2 = "rgba(7fbbb3ee)",
    inactive_border = "rgba(343f44aa)",
    shadow          = 0xee1e2326,
    accent          = "rgba(a7c080ff)",
}
