-- Auto-generated by theme_switcher.py for Hyprland
return {
    name            = "Catppuccin Frappé",
    id              = "catppuccin-frappe",
    base            = "rgba(303446ff)",
    mantle          = "rgba(292c3cff)",
    crust           = "rgba(232634ff)",
    surface0        = "rgba(414559ff)",
    surface1        = "rgba(51576dff)",
    surface2        = "rgba(626880ff)",
    text            = "rgba(c6d0f5ff)",
    subtext0        = "rgba(a5b0d6ff)",
    subtext1        = "rgba(b5bfe2ff)",
    active_border_1 = "rgba(ca9ee6ee)",
    active_border_2 = "rgba(8caaeeee)",
    inactive_border = "rgba(414559aa)",
    shadow          = 0xee232634,
    accent          = "rgba(ca9ee6ff)",
}
