-- Auto-generated by theme_switcher.py for Hyprland
return {
    name            = "Catppuccin Latte",
    id              = "catppuccin-latte",
    base            = "rgba(eff1f5ff)",
    mantle          = "rgba(e6e9efff)",
    crust           = "rgba(dce0e8ff)",
    surface0        = "rgba(ccd0daff)",
    surface1        = "rgba(bcc0ccff)",
    surface2        = "rgba(acb0beff)",
    text            = "rgba(4c4f69ff)",
    subtext0        = "rgba(6c6f85ff)",
    subtext1        = "rgba(5c5f77ff)",
    active_border_1 = "rgba(8839efee)",
    active_border_2 = "rgba(1e66f5ee)",
    inactive_border = "rgba(ccd0daaa)",
    shadow          = 0x55000000,
    accent          = "rgba(8839efff)",
}
