-- =============================================================================
-- Hyprland Dynamic Theme & Color Variables Module
-- =============================================================================
-- Loads the active theme color variables for Hyprland borders, shadows, and decorations.

local theme = {}

-- Default Catppuccin Mocha fallback palette
theme.colors = {
    name            = "Catppuccin Mocha",
    id              = "catppuccin-mocha",
    base            = "rgba(1e1e2eff)",
    mantle          = "rgba(181825ff)",
    crust           = "rgba(11111bff)",
    surface0        = "rgba(313244ff)",
    surface1        = "rgba(45475aff)",
    surface2        = "rgba(585b70ff)",
    text            = "rgba(cdd6f4ff)",
    subtext0        = "rgba(a6adc8ff)",
    subtext1        = "rgba(bac2deff)",
    active_border_1 = "rgba(cba6f7ee)",  -- Mauve
    active_border_2 = "rgba(89b4faee)",  -- Blue
    inactive_border = "rgba(313244aa)",  -- Surface0
    shadow          = 0xee11111b,
    accent          = "rgba(cba6f7ff)",
}

-- Attempt to load active theme variables if generated by theme_switcher.py
local theme_file = os.getenv("HOME") .. "/.config/hypr/theme_vars.lua"
local f = io.open(theme_file, "r")
if f then
    f:close()
    local status, custom_theme = pcall(dofile, theme_file)
    if status and type(custom_theme) == "table" then
        for k, v in pairs(custom_theme) do
            theme.colors[k] = v
        end
    end
end

return theme
