Net/ThemeName "Adwaita-dark"
Net/IconThemeName "Papirus-Dark"
Gtk/ApplicationPreferDarkTheme 1
Gtk/ColorScheme "prefer-dark"
Gtk/DecorationLayout ":close"
Xft/Antialias 1
Xft/Hinting 1
Xft/HintStyle "hintslight"
Xft/RGBA "rgb"
Xft/DPI 98304
